spring:
  multiple:
    datasource:
      # 数据源-1
      test:
        url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&useUnicode=true&autoReconnect=true&failOverReadOnly=false&useAffectedRows=true
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root
        password: root
        # hikari连接池配置 对应 HikariConfig 配置属性类
        hikari:
          poolName: HikariCP-test
          #最小空闲连接数
          minimumIdle: 20
          # 空闲连接存活最大时间，默认10分钟
          idleTimeout: 600000
          # 连接池最大连接数，默认是10
          maximumPoolSize: 100
          # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
          autoCommit: true
          # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
          maxLifetime: 1800000
          # 数据库连接超时时间,默认30秒
          connectionTimeout: 30000
          # 连接测试query
          connectionTestQuery: SELECT 1
        mybatis:
          typeAliasesPackage: io.github.zhoujunlin94.project.meet.repository.db.entity
          mapperLocation: classpath:mybatis/*.xml
          basePackages: io.github.zhoujunlin94.project.meet.repository.db.mapper
          interceptors:
            - clazz: com.github.pagehelper.PageInterceptor
              properties:
                helperDialect: mysql
                reasonable: true
                supportMethodsArguments: true
            - clazz: io.github.zhoujunlin94.meet.tk_mybatis.interceptor.PrintSQLInterceptor
              properties:
                enable: true

  redis:
    host: localhost
    port: 16379
    password: meetredis
    database: 0
    lettuce:
      pool:
        # 最大活跃链接数 默认8（使用负值表示没有限制）
        max-active: 8
        # 最大空闲连接数 默认8
        max-idle: 8
        # 最小空闲连接数 默认0
        min-idle: 1
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1